### ISSUE TITLE
Request for committer status

### ISSUE THREAD

**Issue by mxgrey** [colcon/colcon-ros-cargo#21]
@nuclearsandwich Similar to https://github.com/colcon/colcon-cargo/issues/31 this repo currently suffers from an absence of active maintainers.

There's a much anticipated PR https://github.com/colcon/colcon-ros-cargo/pull/19 that is a crucial prerequisite for getting this colcon extension released on packagecloud, but it's currently blocked by the absence of reviews by anyone with committer status.

I'd like to request committer status for myself and @luca-della-vedova on the same rationale as the request for `colcon-cargo` since the two are strongly related and even interlinked.

**Comment by esteve** [comment]
@mxgrey thanks for the offer, I've added @luca-della-vedova as a maintainer since he's the one who's been contributing to the project

**Comment by mxgrey** [comment]
Thanks @esteve , then I'll look forward to Luca's PR getting reviewed by an existing maintainer since he can't approve his own for the merge requirements to be met.

**Comment by esteve** [comment]
@mxgrey I just merged #19 , for some reason I thought @maspe36 and @jhdcs were already maintainers of this repo, so I didn't check #19 and assumed it got merged a while ago.

**Comment by mxgrey** [comment]
Thanks, I believe the release onto packagecloud is also blocked on https://github.com/colcon/colcon-ros-cargo/pull/22 which is blocked on https://github.com/colcon/colcon-cargo/pull/39 .

Fortunately https://github.com/colcon/colcon-cargo/pull/39 does have at least one approval from a maintainer (Steven!). Later this week I'll do a review of that one myself and approve+merge if everything seems reasonable since I have maintainer status on `colcon-cargo`. But after that https://github.com/colcon/colcon-ros-cargo/pull/22 will be waiting for a `colcon-ros-cargo` maintainer for approval.
